"""Schema definitions for comprehensive profile outputs."""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class ModelTrace(BaseModel):
    """Track whether the final comprehensive result came from accepted LLM output."""

    mode: str = "unknown"
    used_llm: bool = False
    model_name: str = ""
    fallback_reason: str = ""


class ComprehensiveProfileStructuredResult(BaseModel):
    """Structured output generated by comprehensive skill."""

    agent_name: str = "comprehensive_profile_agent"
    uid: str
    status: str = "ok"
    summary: str = ""
    persona: str = "unknown"
    segment: str = ""
    segment_name: str = ""
    overall_risk: str = ""
    overall_value: str = ""
    confidence: str = ""
    data_completeness: dict[str, Any] = Field(default_factory=dict)
    behavior_tags: dict[str, Any] = Field(default_factory=dict)
    financial_tags: dict[str, Any] = Field(default_factory=dict)
    upstream_summaries: dict[str, Any] = Field(default_factory=dict)
    metrics: dict[str, Any] = Field(default_factory=dict)
    tags: list[str] = Field(default_factory=list)
    model_trace: ModelTrace = Field(default_factory=ModelTrace)
