"""Repository protocol definitions for the M2D knowledge-base skeleton."""

from __future__ import annotations

from typing import Protocol

from app.knowledge_base.schemas import (
    KnowledgeBase,
    KnowledgeDocument,
    KnowledgeDocumentVersion,
    KnowledgeIngestJob,
    KnowledgeIngestJobRuntimeState,
)


class KnowledgeBaseRepository(Protocol):
    def create(self, kb: KnowledgeBase) -> KnowledgeBase: ...
    def get(self, kb_id: str) -> KnowledgeBase | None: ...
    def list(self) -> list[KnowledgeBase]: ...
    def update(self, kb: KnowledgeBase) -> KnowledgeBase: ...


class KnowledgeDocumentRepository(Protocol):
    def create_document(self, document: KnowledgeDocument) -> KnowledgeDocument: ...
    def get_document(self, doc_id: str) -> KnowledgeDocument | None: ...
    def list_documents(self, kb_id: str) -> list[KnowledgeDocument]: ...
    def update_document(self, document: KnowledgeDocument) -> KnowledgeDocument: ...
    def create_version(self, version: KnowledgeDocumentVersion) -> KnowledgeDocumentVersion: ...
    def get_version(self, version_id: str) -> KnowledgeDocumentVersion | None: ...
    def list_versions(self, doc_id: str) -> list[KnowledgeDocumentVersion]: ...
    def update_version(self, version: KnowledgeDocumentVersion) -> KnowledgeDocumentVersion: ...


class KnowledgeIngestJobRepository(Protocol):
    def create(self, job: KnowledgeIngestJob) -> KnowledgeIngestJob: ...
    def get(self, job_id: str) -> KnowledgeIngestJob | None: ...
    def update(self, job: KnowledgeIngestJob) -> KnowledgeIngestJob: ...
    def list_by_version(self, version_id: str) -> list[KnowledgeIngestJob]: ...


class KnowledgeIngestJobRuntimeStateRepository(Protocol):
    def get(self, job_id: str) -> KnowledgeIngestJobRuntimeState | None: ...
    def upsert(self, state: KnowledgeIngestJobRuntimeState) -> KnowledgeIngestJobRuntimeState: ...
